### ISSUE TITLE
Primary key requirement

### ISSUE THREAD

**Issue by dzhus** [ThibTrip/pangres#11]
Thank you for the library.

I'm wondering what's the reason for a hard requirement for Dataframes to have an index which is the primary key of the SQL table? If we're upserting foreign data that doesn't have a primary key in a Postgres table with a unique constraint defined, we'd still want to simply do `INSERT .. ON CONFLICT DO NOTHING`:

```sql
CREATE TABLE whatever (
  message text, 
  author text
);

CREATE UNIQUE INDEX whatever_dedup ON whatever (md5(message || author));
```

It appears that https://github.com/ThibTrip/pangres/blob/91330fff5dd4de446f757d2877a4aaca53d5547a/pangres/helpers.py#L116-L129 effectively expects me to create a synthetic key on application side, but why?

**Comment by ThibTrip** [comment]
Thanks for posting an issue @dzhus!

The purpose of pangres is to update existing data according to primary keys in a SQL table OR create a SQL table with primary keys. <code>df.to_sql</code> cannot do any of this at this time. I suggest you look at the ["Upsert" page](https://github.com/ThibTrip/pangres/wiki/Upsert) in the wiki if you haven't already. It is (for now at least) **not meant for table without primary keys**.

The reason why pangres expects a named index is because by setting columns of your DataFrame as the index you show pangres that those columns are the primary keys. pangres creates a Python SQL table model from the DataFrame (via pandas which itself uses sqlalchemy) and **in this model it sets the index as primary key**.

I suppose this could be implemented in a different way such as by looking up the primary keys in the SQL table and checking them in the pandas DataFrame. Then we could add an <code>index</code> parameter (True/False) and have the primary keys placed anywhere in the pandas DataFrame. I am not sure how easely this can be done.

Anyhow, if I understand correctly what you want to do is something like <code>df.to_sql(if_exists='append', ...)</code> with pangres? So ignoring primary keys completely and letting the driver raise on duplicates just like pandas? This would be a simple <code>INSERT</code> statement not a [INSERT... ON CONFLICT DO NOTHING](https://www.postgresql.org/docs/9.5/sql-insert.html) since such a statement implies there are columns to ignore conflicts **on**.
If you need this I suppose we could add a value to the parameter "if_row_exists" such as "ignore_pk"!?

**Comment by dzhus** [comment]
> df.to_sql(if_exists='append', ...) with pangres? 

Yes.

> since such a statement implies there are columns to ignore conflicts on.

No, it would be an `INSERT ... ON CONFLICT DO NOTHING` because there's a unique constraint that we want to effectively deduplicate data on (like `whatever_dedup` in my example above).

I ended up with the following:

```python
def _pg_upsert(pd_table, conn, keys, data_iter):
    rows = [dict(zip(keys, r)) for r in data_iter]
    table = pd_table._create_table_setup()
    insert_stmt = insert(table).values(rows).on_conflict_do_nothing()
    conn.execute(insert_stmt)
```
and then using standard `pandas.to_sql`:
```python
rc = batch.to_sql(msg_table, schema=pg_schema,
                  con=tran,
                  method=_pg_upsert,
                  if_exists='append',
                  index=False)
```

**Comment by dzhus** [comment]
It's probably resolved – as in I didn't use pangres eventually because the use case is slightly different.

**Comment by ThibTrip** [comment]
> No, it would be an INSERT ... ON CONFLICT DO NOTHING because there's a unique constraint that we want to effectively deduplicate data on (like whatever_dedup in my example above).

Oh ok I didn't know it could work like that sorry 😳!

Glad you could figure something out for your use case!
