### ISSUE TITLE
It is actually compatible with unique constraint

### ISSUE THREAD

**Issue by LawrentChen** [ThibTrip/pangres#12]
Hi, ThibTrip. Although in the usage instruction you indicate that  `pangres.upsert` function works by **primary key**, which must be set as the index of DataFrame. And you also wrote 'we don't want autoincremented PK' in the examples. But I found that it is actually compatible with **unique constraint and an autoincremented PK** (at least in MySQL 5.7). 

Please take a look.

```mysql
-- Here the `row_id` is the auto-incremented primary key
-- `order_id` and `product_id` make up of the unique constraint
-- let's say a single order can have more than one kind of product

CREATE TABLE `order_info` (
  `row_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto_incremented_ID',
  `order_id` varchar(5) NOT NULL DEFAULT '-9999' COMMENT 'order_id',
  `product_id` varchar(5) NOT NULL DEFAULT '-9999' COMMENT 'product_id',
  `qty` int(11) DEFAULT NULL COMMENT 'purchase_quantity',
  `refund_qty` int(11) DEFAULT NULL COMMENT 'refund_quantity',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'last_update_time',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'first_create_time',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `main` (`order_id`,`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Order Info'
```

Insert the origin values first.

| order_id | product_id |  qty | refund_qty |
| :------- | :--------- | ---: | ---------: |
| A0001    | PD100      |   10 |          0 |
| A0002    | PD200      |   20 |          0 |
| A0002    | PD201      |   22 |          0 |

```python
import pangres

old_data = {'order_id': ['A0001', 'A0002', 'A0002'],
            'product_id': ['PD100', 'PD200', 'PD201'],
            'qty': [10, 20, 22],
            'refund_qty': [0, 0, 0]}
old_df = pd.DataFrame(old_data)
old_df = old_df.set_index(['order_id', 'product_id'])

# lets suppose engine has been defined somehow

pangres.upsert(engine=engine,
               df=old_df,
               table_name='order_info',
               if_row_exists='update')
```

Then we get

| row_id | order_id | product_id |  qty | refund_qty | update_time         | create_time         |
| -----: | :------- | :--------- | ---: | ---------: | :------------------ | :------------------ |
|      1 | A0001    | PD100      |   10 |          0 | 2020-06-28 20:31:04 | 2020-06-28 20:31:04 |
|      2 | A0002    | PD200      |   20 |          0 | 2020-06-28 20:31:04 | 2020-06-28 20:31:04 |
|      3 | A0002    | PD201      |   22 |          0 | 2020-06-28 20:31:04 | 2020-06-28 20:31:04 |

Next, upsert the new df as below:

| order_id | product_id |  qty | refund_qty |
| :------- | :--------- | ---: | ---------: |
| A0001    | PD100      |   10 |          0 |
| A0002    | PD200      |   20 |          0 |
| A0002    | PD201      |   22 |          2 |
| A0003    | PD300      |   30 |          0 |

```python
new_data = {'order_id': ['A0001', 'A0002', 'A0002', 'A0003'],
            'product_id': ['PD100', 'PD200', 'PD201', 'PD300'],
            'qty': [10, 20, 22, 30],
            'refund_qty': [0, 0, 2, 0]}
new_df = pd.DataFrame(new_data)
new_df = new_df.set_index(['order_id', 'product_id'])

pangres.upsert(engine=engine,
               df=new_df,
               table_name='order_info',
               if_row_exists='update')
```

The result is completely as expected!

| row_id | order_id | product_id |  qty | refund_qty | update_time             | create_time             |
| -----: | :------- | :--------- | ---: | ---------: | :---------------------- | :---------------------- |
|      1 | A0001    | PD100      |   10 |          0 | 2020-06-28 20:31:04     | 2020-06-28 20:31:04     |
|      2 | A0002    | PD200      |   20 |          0 | 2020-06-28 20:31:04     | 2020-06-28 20:31:04     |
|      3 | A0002    | PD201      |   22 |          2 | **2020-06-28 20:37:13** | 2020-06-28 20:31:04     |
|      4 | A0003    | PD300      |   30 |          0 | **2020-06-28 20:37:13** | **2020-06-28 20:37:13** |

The `update_time` field only changed in the last two records, while the first two remain what they should be.

---

I would suggest you add this feature description to the README (and nothing have to change in the code), since I was so excited to find your repo to solve the upsert issue of pandas so nicely , but then turned sad when I read it only supporting primary key without auto increment. Only after I took a closer look at the code and carefully ran a test can I find it actually works with auto increment and unique constraint (at leat in MySQL).

**Comment by LawrentChen** [comment]
BTW, I first met this upsert issue during about July or August last year, and I never expect this issue has lasted for nearly four years in the official repo. But I haven't found your package at that time, sad...

Then I made my own (very ugly) way to deal with it. Recently I decided to upload it to pypi just to learn how to package and release the code, no matter how ugly it is (I am not a professional engineer). When I look at the discussion in [issue #14553](https://github.com/pandas-dev/pandas/issues/14553) again, it led me to your repo. 

My package is [pandas_upert_to_mysql](https://pypi.org/project/pandas-upsert-to-mysql) and I suggest yours in the first line of description, hoping more people with the same problem can find pangres. And again, my gratitude to your work.

**Comment by ThibTrip** [comment]
Hello! Thanks for the kind words! I am pleasantly surprised that upserting using unique keys works with pangres.

I was writing tests using your example with sqlalchemy ORM and could reproduce similar results for MySQL. I shall do a **PR** later with a README update and a new test module showing that we can also use unique keys. And where did I write that it **does not work with auto incremented primary keys** :see_no_evil:?

Now that you mention it I also find it crazy that this lasted 4 years :open_mouth:! I am also not that much of a professional I just use Jupyter Lab (and back then the notebook) like a madman to try everything possible :monkey: then I do some proper functions/classes/modules/... and as rigorous as possible testing. I developped <code>pangres</code> using [jupytext](https://github.com/mwouts/jupytext) in order to have Python files that behave like notebooks (and before that I was using post save hooks to pair notebooks with python scripts).

I looked very quickly at [pandas_upert_to_mysql](https://pypi.org/project/pandas-upsert-to-mysql) and noticed you use the same strategy for MySQL (prefix with IGNORE or use method on_duplicate_key_update from mysql insert), cool :sunglasses: !

I will use a simpler example for my tests as this was too hard to reproduce in PostgreSQL (due to the auto updating timestamp). I did not even bother trying with SQLite :see_no_evil: but I did try several things which were "supposed to work" (e.g. argument <code>onupdate=func.now()</code> for the update_time column definition). Anyhow you can see below how I tested your example (or something roughly identical at least) with sqlalchemy ORM in case you are interested. What's under the chapter "Unique key test" in the code below was supposed to go in a function for pytest but as I said I'll have to use a simpler example :stuck_out_tongue: .

<details>
 <summary>Test</summary>


```python
"""
This module tests if we can use a unique key instead of a primary key
for upserting.

Thanks to LawrentChen on GitHub for pointing out this is possible.
See https://github.com/ThibTrip/pangres/issues/12
"""
import pandas as pd
import datetime
from pangres import upsert
from pangres.tests.conftest import drop_table_if_exists
from sqlalchemy import (INTEGER, TIMESTAMP, VARCHAR, MetaData, Column,
                        UniqueConstraint, func, text)
from sqlalchemy.ext.declarative import declarative_base
```

# Helpers


```python
table_name = 'test_unique_key'

def create_test_table(engine, schema):
    Base = declarative_base(bind=engine)

    class TestUniqueKey(Base):
        """
        Example table model similar to the table LawrentChen on GitHub provided
        in issue https://github.com/ThibTrip/pangres/issues/12
        """
        __tablename__ = table_name
        __table_args__ = (UniqueConstraint('order_id', 'product_id'),
                          {'schema':schema})

        row_id = Column(INTEGER, primary_key=True, comment='auto_incremented_ID')
        order_id = Column(VARCHAR(5), nullable=False, server_default='-9999')
        product_id = Column(VARCHAR(5), nullable=False, server_default='-9999')
        qty = Column(INTEGER, nullable=True, comment='purchase_quantity')
        refund_qty = Column(INTEGER, nullable=True, comment='refund_quantity')
        update_time = Column(TIMESTAMP(), nullable=False,
                             server_default=text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), 
                             comment='last_update_time')
        create_time = Column(TIMESTAMP(), nullable=False,
                             server_default=text('CURRENT_TIMESTAMP'),
                             comment='first_create_time')

    Base.metadata.create_all()
```

# Config


```python
engine = 'SOME_ENGINE'
schema = None
```

# Unique key test


```python
# create our test table
drop_table_if_exists(engine=engine, schema=schema, table_name=table_name)
create_test_table(engine=engine, schema=schema)

# ADD INITIAL DATA
data_old = {'order_id': ['A0001', 'A0002', 'A0002'],
            'product_id': ['PD100', 'PD200', 'PD201'],
            'qty': [10, 20, 22],
            'refund_qty': [0, 0, 0]}
df_old = pd.DataFrame(data_old).set_index(['order_id', 'product_id'])
upsert(engine=engine, df=df_old, schema=schema, table_name='test_unique_key', if_row_exists='update')

# do some verifications to check if the initial data was added properly
namespace = f'{schema}.{table_name}' if schema is not None else table_name
df = pd.read_sql(f'SELECT * FROM {namespace}', con=engine, index_col='row_id')
## columns update_time and create_time should contain the same datetime
## we do not verify it since it changes every time (it is set to the current time)
assert df[['update_time', 'create_time']].stack().unique().size == 1
assert df[['update_time', 'create_time']].notna().all().all()
## check content of other other columns
subset_cols = ['order_id', 'product_id', 'qty', 'refund_qty']
df_subset = df[subset_cols]
df_subset_expected = (pd.DataFrame([[1, 'A0001', 'PD100', 10, 0],
                                   [2, 'A0002', 'PD200', 20, 0],
                                   [3, 'A0002', 'PD201', 22, 0]],
                                   columns=['row_id'] + subset_cols)
                      .set_index('row_id'))
pd.testing.assert_frame_equal(df_subset, df_subset_expected)
df
```

|   row_id | order_id   | product_id   |   qty |   refund_qty | update_time         | create_time         |
|---------:|:-----------|:-------------|------:|-------------:|:--------------------|:--------------------|
|        1 | A0001      | PD100        |    10 |            0 | 2020-06-30 00:00:34 | 2020-06-30 00:00:34 |
|        2 | A0002      | PD200        |    20 |            0 | 2020-06-30 00:00:34 | 2020-06-30 00:00:34 |
|        3 | A0002      | PD201        |    22 |            0 | 2020-06-30 00:00:34 | 2020-06-30 00:00:34 |

```python
# ADD NEW DATA
data_new = {'order_id': ['A0001', 'A0002', 'A0002', 'A0003'],
            'product_id': ['PD100', 'PD200', 'PD201', 'PD300'],
            'qty': [10, 20, 22, 30],
            'refund_qty': [0, 0, 2, 0]}
            
df_new = pd.DataFrame(data_new).set_index(['order_id', 'product_id'])

# here we would check if data was properly upserted by comparing timestamps...
upsert(engine=engine, df=df_new, schema=schema, table_name='test_unique_key', if_row_exists='update')
df = pd.read_sql(f'SELECT * FROM {namespace}', con=engine, index_col='row_id')
df
```
|   row_id | order_id   | product_id   |   qty |   refund_qty | update_time         | create_time         |
|---------:|:-----------|:-------------|------:|-------------:|:--------------------|:--------------------|
|        1 | A0001      | PD100        |    10 |            0 | 2020-06-30 00:00:34 | 2020-06-30 00:00:34 |
|        2 | A0002      | PD200        |    20 |            0 | 2020-06-30 00:00:34 | 2020-06-30 00:00:34 |
|        3 | A0002      | PD201        |    22 |            **2** | **2020-06-30 00:00:36** | 2020-06-30 00:00:34 |
|        4 | A0003      | PD300        |    30 |            0 | **2020-06-30 00:00:36** | **2020-06-30 00:00:36** |


</details>

**Comment by LawrentChen** [comment]
Glad to have your response! You showed me it is possible to use emoji in markdown, nice😎.

### First about the primary key

> And where did I write that it does not work with auto incremented primary keys 🙈?

'# we don't want autoincremented PK \-\_\-"...', I quote from [examples.py line19](https://github.com/ThibTrip/pangres/blob/91330fff5dd4de446f757d2877a4aaca53d5547a/pangres/examples.py#L19)...You might have forgotten this 😅.

The problem in MySQL is that if you do want an auto increment, then you will have to include it in the primary key, like `{'primary_key': ['auto-increment', [unique_constraint_columns_in_real]]}`. And of course, with this pk there will be no update at all, just keep inserting duplicates with different row_id.

And my problem is just knowing something about MySQL, but nothing about other databases at all 😭. Maybe this auto increment won't be a problem in PostgreSQL or any others, I don't know...(I am planning learn more of them.)

**Comment by LawrentChen** [comment]
### Auto update timestamp in other DBs

Indeed you should design a simpler example, which can suit with all major DBs you decide to support (for now, MySQL, PostgreSQL and SQLite, I think). After some search in SQLAlchemy docs and StackOverFlow, it seems that other DBs have to use something like **trigger** defined natively (outside SQLAlchemy) in order to achieve such an auto update timestamp. Only MySQL can use `server_default` to declare in SQLAlchemy ORM. 

I can see both of us hope to get the job done in pure python. But maybe it will be a good idea to leave this part to DDL in SQL itself. **Define the table natively first (handle the dirty work if you do want them), after that use pangres to upsert to it**. And maybe this is one of the reasons why the officials took so long to deal with the upsert issue 😅. 

>"...whether Pandas should remain simple to protect users that have a poorly designed database, or have more functionalities"

As they said, keeping pratice consistent among different databases isn't quite easy I guess.

Btw, your definition using `text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')` is something I haven't known...I used to use the trick that the first timestamp field defined in SQLAlchemy ORM to MySQL will be set as auto updated 😅. Now I learned your way to make this more explicit, thanks 😊!

Below are some related info I found (maybe you have known, but...just leave them here in collapse).
<details>
<summary>Refer Links</summary>
</br>
<b>SQLAlchemy</b> </br>
<a href='https://docs.sqlalchemy.org/en/13/dialects/mysql.html#rendering-on-update-current-timestamp-for-mysql-s-explicit-defaults-for-timestamp'>on-update-timestamp OMR definition for MySQL</a></br>
<a href='https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#compatibility-with-sqlite3-native-date-and-datetime-types'>timestamp for SQLite</a> (I don't understand this part)</br>
And I haven't find something like those two above for PostgreSQL</br>
<a href='https://docs.sqlalchemy.org/en/13/core/defaults.html#marking-implicitly-generated-values-timestamps-and-triggered-columns'>using FetchedValue</a> (I haven't tested if this works, but I guess it will only work in ORM selecting.)</br>
</br>
<b>StackOverFlow</b></br>
<a href='https://stackoverflow.com/questions/13370317/sqlalchemy-default-datetime?r=SearchResults#33532154'>a general answer</a>
</details>

**Comment by LawrentChen** [comment]
### Miscellaneous

As I can tell, you are much more proficient than me, but still modest 😄.

I also began learning python by Jupyter Notebook. That is such a great tool combing writing, coding and presentation. Now I usually use Pycharm and Jupyter lab, planning to build an online environment with Jupyter Hub (feeling difficult 😂).

Your methods to unpack the DataFrame, retrieve the metadata through `pd.io.sql.SQLTable` and change its bind to SQLAlchemy engine are just impressive. I often upsert data crawled by spider, which I can't control them in every detail. Keeping the values aligned by column names reliefs me from worrying if the order of columns  would change in new DataFrame, fantasic! In my own package, I just bypassed this problem using temporary table, at a huge cost of perfomance (and also ugly 😭).

I still know little about test. Your code is good and I learn many from them. Hope one day I can contribute a useful PR to help rather than just writing issues 😂.

**Comment by ThibTrip** [comment]
I can't really remember what was the issue with the auto incrementing key but the comment you were pointing at is merely a module filled with examples which is used for tests, docs and if a user wants to try pangres quickly. I recall that for some reason testing with an auto-incrementing primary key was complicated wich is why I ended up using a instead VARCHAR. But I removed this comment anyways in my new [pull request](https://github.com/ThibTrip/pangres/pull/14). This PR changes the documentation to indicate we can use unique keys. Actually it does a little more than that I kind of got carried away (e.g. I changed the script for generating the documentation and fixed the yml file for code coverage). Maybe you want to give me your **opinion on the documentation changes in the PR** before I merge it?

I also added tests with unique keys in a previous [PR](https://github.com/ThibTrip/pangres/pull/13). I forgot to ask you before merging sorry. Hope the test is what you had in mind. I just removed the timestamp columns because that was unnecessarily complicated for testing. I did see what you mentioned with triggers yes. Fortunately I have never needed such a use case in my work :see_no_evil: or I would just do <code>datetime.datetime.now().astimezone(datetime.timezone.utc)</code> and call it a day (it did not matter much for me but doing that server side would be more accurate and most likely better for performance).

For JupyterHub I suppose using docker should make the task much easier. Obviously you'll have to learn docker but it should be worth it (plus docker is used everywhere :neutral_face:). See [docker page on JupyterHub website](https://jupyterhub.readthedocs.io/en/stable/quickstart-docker.html) (they provide the link to the docker image on docker hub with detailed instructions).
As for testing I can heavily recommand pytest. It's very convenient and flexible. I am not sure I understand everything with parameterizing and generating tests though. I have used parameters in my other public library npdoc_to_md and in pangres I just generate tests for each database type. I learnt a few things about pytest by looking at tests in pandas repo.
And keep writing issues :+1: . I don't think everyone does that when they notice something's not right.

**Comment by LawrentChen** [comment]
Thank you for taking my opinion in consideration. I've looked at both two PRs and I believe they are clear enough for new users. No need to feel sorry for not asking me before merging, I am already quite satisfied for being involved 😝.

Docker and pytest are right there in my learning roadmap, also considering Kubernetes. Happy to have these right targets. And I will try npdoc_to_md in the future. It seems can be used together with document generator like Sphinx/Jupinx.

And after you finish, I believe this issue can be closed anytime you wish. Have a nice day! 👍

**Comment by osdiego** [comment]
Hi, guys!

Ty for everything. I'm using this with MySQL and it works nicely, but I could not set it up properly with SQL Server. 
Do you have any ideia why?

**Comment by ThibTrip** [comment]
@osdiego my first thought was the MySQL version but the ON...CONFLICT clause seems to have been there forever.
Did you also check that the index of your pandas DataFrame contains the column(s) corresponding to the unique index or primary key in the database?
Other than that I can't help you without seeing some code :(. If you are upserting into an existing table you can also post the DDL.
