### ISSUE TITLE
make `add_new_columns` default to `False`

### ISSUE THREAD

**Issue by lsloan** [ThibTrip/pangres#15]
Pangres' upsert function is extremely useful.  However, the default value for its `add_new_columns` argument should be `False`.  Adding columns to a table automatically is not what one would expect from an insert or update function, so it shouldn't be automatic with an upsert one, either.  It's a great optional feature, but it shouldn't be done unless explicitly requested.

For that matter, `create_schema` should also default to `False`.

**Comment by rajrohan** [comment]
@lsloan Yes you are right but in that pangres package should be able to upset by removing those new columns from the data frame. Otherwise, `add_new_columns` default `false` with creating an issue of the column does not exist in the database table.

**Comment by ThibTrip** [comment]
Thanks a lot for your inputs! You are right (both of you) that makes a lot of sense. So yes, <code>create_schema</code> and <code>add_new_columns</code> should default to <code>False</code> and an error should be raised on a missing column when <code>add_new_columns</code> is <code>False</code>.

Since some people are already using the library I suppose it would be a good idea to release a minor version soon (I should be able to do that this week) to introduce a deprecation.
Then I can do another release in say one month (or a bit earlier if a new feature come up) where I can make the breaking change.

What do you think about my idea for the deprecation? It's not my first library (far from it actually) but I haven't had this problem that often yet. I did the same thing when I renamed "pg_upsert" to simply "upsert".

**Comment by lsloan** [comment]
I'm not sure what form the deprecation would take for changing the default value of an argument.  To me, deprecation means a warning that a feature will be removed and won't appear in future versions.  In this case, we're not suggesting `add_new_columns` be removed. 
 Maybe I'm obsessing over the meaning of "deprecation".

Do you mean that the documentation would be updated to warn users that the default value will change in a future release?

As for gradually working up to a breaking change after some time, I think that's reasonable.  Probably most of us using this module now are aware of how this feature works (perhaps after being surprised by it).  If you think the number of users will grow rapidly, then waiting about a month from now might be too slow.  This change would benefit new users the most, I think.

PS: I was trying to think of the adage that applies to this issue.  I finally remembered the "Principle of Least Astonishment" (POLA). 😉
