### ISSUE TITLE
[Question] Write DataFrame index as a column argument

### ISSUE THREAD

**Issue by belskianton** [ThibTrip/pangres#24]
Pandas.to_sql() allows to specify `index: bool` argument, which can be set to `False` to avoid writing dataframe index as a column. It's a good option in case a table has an auto increment primary key which is not in DataFrame columns. 
Is it possible to add such an arg (Index:bool) to pangres.upsert()?

**Comment by ThibTrip** [comment]
Hello @belskianton!

`pangres` always needs "key(s)" to compare records existing in a database table with a DataFrame.

I have chosen to use the DataFrame index for such comparison (which means in some cases users will have to temporarily set the index to some column(s) only for the `upsert` function). Of course I could have designed the library differently and use an argument such as  `compare_with_columns`. In any case I don't see any reason why you would have to save columns that you actually do not need to save.

Of course when you say:
> avoid writing dataframe index as a column

You cannot avoid this since the index is required for comparison purposes. And it **must already exist in the database** anyways (unless you are creating a new table). Are you sure you have set the correct index for the DataFrame though? Because this following statement of yours confuses me:
> in case a table has an auto increment primary key which is not in DataFrame columns

What are you trying to do? Perhaps you would like to use another DataFrame column to compare existing records? In this case you can temporarily set this DataFrame column as an index for the `upsert` function. Let us say you have the unique index `id` then you can do `upsert(df=df.set_index('id'), **other_arguments)` and `df` will not be modified (as `df.set_index` returns a copy by default).

Or do you want to compare `pandas`' default index (ranging from 0 to the length of the DataFrame) with your auto-incremented key? In this case you can temporarily set the name of the index to the name of the auto increment key . E.g. `upsert(df=df.rename_axis(index='id'), **other_arguments)`

Or maybe you don't want to do an INSERT+UPDATE operation but simply append? In which case you could use `df.to_sql(if_exists='append')`

A **Python example** would be most welcome if possible :see_no_evil: (anonymize some variables if necessary)!

**Comment by belskianton** [comment]
I got it. I have unique constraint on multiple columns, so I can just set the columns as an index. I thought that pangres cannot process unique constraint on multiple columns. Thanks for your answer!

**Comment by ThibTrip** [comment]
Great! I will close this issue now. If there is anything else, feel free to reopen it!
