### ISSUE TITLE
how to write to a table with only one column

### ISSUE THREAD

**Issue by lfjbb** [ThibTrip/pangres#26]
if the dataframe only have index nothing inserted
if the dataframe have an index and column with the same name， raise a error： There cannot be duplicated names amongst index levels and/or columns!
if the dataframe have an index and column with the different name， raise a error ：sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'date1' in 'field list'")

**Comment by ThibTrip** [comment]
Hello, sorry for answering late. So you have multiple problems :open_mouth: ?

# 1. if the dataframe only have index nothing inserted

Yes I need to fix that, this is problematic :crying_cat_face: . In the last cell in the screenshot below we should have the index. I can get on it this week.

![image](https://user-images.githubusercontent.com/40694343/102184839-68e5f800-3eb0-11eb-97b6-3c53c9546500.png)

# 2. if the dataframe have an index and column with the same name, raise a error...

Well yes this is expected. I don't see the problem here. For MySQL, postgres, SQlite or any other SQL database for that matter the column "test" is duplicated. It's just pandas that's making a distinction here because "test" exists as index level and column.  

![image](https://user-images.githubusercontent.com/40694343/102185276-16f1a200-3eb1-11eb-9522-32e0da5bf5a8.png)

# 3. if the dataframe have an index and column with the different name， raise a error...

I don't understand this problem sorry. The error you got seems to indicate that column `date1` is missing. Set argument `add_new_columns` to True as demonstrated below to create it automatically.

![image](https://user-images.githubusercontent.com/40694343/102186147-78fed700-3eb2-11eb-8a33-bef445f38b6e.png)

**Comment by lfjbb** [comment]
thanks for your reply.
actrually， I have a table("trade_dates") only have a column "date", and I have tried 3 ways to upsert it. 
finally, I modify core.py,  line 203
`if df.empty:`
to
`if df.empty and df.index.empty:`

**Comment by ThibTrip** [comment]
@lfjbb yes you are right this line was indeed one of the problems I had to fix :+1: . The new release (2.2.3) should handle DataFrames with no columns now (only index levels).

Feel free to reopen the issue and comment if there is anything else.

Thanks for your help :+1:
