### ISSUE TITLE
Metric number of inserted rows

### ISSUE THREAD

**Issue by jopfeffe** [ThibTrip/pangres#32]
Hi,

I wonder if there is a way to get the number of successfully inserted rows?

In sqlalchemy I can get it cia *.rowcount*

It there something equal in pangres?

King regards

**Comment by ThibTrip** [comment]
Hello 🙂!

Thanks for your question! I know what you mean but it's a bit difficult since by default the library [inserts in chunks](https://github.com/ThibTrip/pangres/blob/master/pangres/helpers.py#L494-L500).
This means I would have to yield an object for the user between each insert, which would obviously breaks the current usage.

But I suppose a flexible behavior could be achieved by adding a parameter. Not sure how I would name this parameter :thinking:... Say I would call the parameter `yield_chunks` then in pseudo code it would look like this (I'm writing this out of my hat I have no idea if the object sqalchemy gives back to me in this case has a `rowcount` attribute):

```python
import pandas as pd
from pangres import upsert

df = pd.DataFrame(...)
iterator = upsert(df, ..., yield_chunks=True)

for result in iterator:
    updated_rows = result.rowcount
```

I have a lot of work currently so I can't look into right now. Perhaps this weekend I can check it...

**Comment by jopfeffe** [comment]
What you described in that pseudo code is exactly what I'm looking for. Would love to see that feature in an upcoming release.

**Comment by ThibTrip** [comment]
Oh great okay :+1:! I shall be getting some more free time so I hope I can look into it soon :disappointed_relieved:.

**Comment by ThibTrip** [comment]
Sooo I hope you are happy with the new feature @jopfeffe ! Sorry again for the delay. You know I thought I would not need this feature but it's actually quite cool. One can make a simple progress bar like this:

```python
from math import ceil
import pandas as pd
from pangres import upsert

df = pd.DataFrame(...)
chunksize = 100
nb_chunks = ceil(len(df)/chunksize)
iterator = upsert(df, ..., chunksize=chunksize, yield_chunks=True)

for ix, result in enumerate(iterator):
    print('{ix+1}/{nb_chunks} upserted', end='\r')
```

Of course this is pseudo code (and I am not sure if everything's correct) but you get the idea. **`end='\r'`** is especially important in the print since that prints on the same line.
