### ISSUE TITLE
Does not upsert

### ISSUE THREAD

**Issue by igorwolford** [ThibTrip/pangres#39]
I have a df with multi-index of 4 columns (all named and no values are Null), which match the PK of the table in PostgreSQL.
The database is not updated on upsert. No errors are raised.
How can I debug this and make it work?

SQLAlchemy 1.4.26
psycopg2 2.9.1
pandas 1.3.2
pangres 2.3.1

```
    iterator = pangres.upsert(engine, df_1[0:1], 'my_table', if_row_exists='update', chunksize=1,  yield_chunks=True) 
    for result in iterator:
        print(f'{result.rowcount} row(s) updated')
```
Results in:
```
sqlalchemy.engine.Engine BEGIN
sqlalchemy.engine.Engine INSERT INTO ... ON CONFLICT ( ...the_4_columns... ) DO UPDATE SET ...
sqlalchemy.engine.Engine [no key 0.00048s] { .... }
sqlalchemy.engine.Engine ROLLBACK
1 row(s) updated
```

I tried running pangres tests - some pass, some fail. Even though I'm using PostgreSQL, I had to install MySQL and there appears to be some issue with SQLAlchemy and the latest MySQL. Stackoverflow suggests to rollback the versions, etc. A bit too much work for me at the moment to debug a database that I'm not going to use. So also a recommendation to enable tests with just a single database at a time. Thank you.

**Comment by ThibTrip** [comment]
Hi, thanks for posting an issue!

Can you give me an example DataFrame to reproduce the error? I can't  troubleshoot it otherwise 😕.

Being able to do tests on one or more databases instead of always all of them is a good idea, thanks!
I am very busy atm but I'll look it up as soon as I can.

I have some suggestions for you out of the blue (without an example it's hard to pinpoint the issue):

1) try giving the data types to pangres.upsert with the parameter `dtype`, for instance:

```python
from pangres import upsert
from sqlalchemy import TEXT

upsert(... dtype={"column" :Text})
```

2) if you have timestamps pay attention to the timezone. Using UTC is best.

3) try the query in postgres directly, see if it works there

That being said it says one row was updated so it means that it found a match 🤔...

This definitely needs more investigation.

EDIT: I tried running my tests multiple times and cannot get anything to fail :neutral_face: so that worries me too.

Can you give me the versions of the databases you are using too?

**Comment by igorwolford** [comment]
Ok, got it figured out. The problem was in SQLAlchemy engine definition.
When 'future=True' is set, it won't commit any changes I make, including even the execution of simple manual statements. 
When I removed it, everything worked.

```
>>> engine = create_engine(engine_str, echo=True, future=True)  # rolls back any changes and does not commit
...
sqlalchemy.engine.Engine ROLLBACK
1 row(s) updated

>>> engine = create_engine(engine_str, echo=True)  # works as intended
...
sqlalchemy.engine.Engine COMMIT
1 row(s) updated
```

For the purposes of pangres, I wonder if it is possible to differentiate between ROLLBACK and COMMIT before displaying if rows were updated, so there will be less confusion.
Thanks again!

**Comment by ThibTrip** [comment]
Hi, glad you worked it out! I could not sleep the other day so I finished a lot of the cool stuff I had planned for `pangres`.

# Differentiating between `ROLLBACK` and `COMMIT`

"For the purposes of pangres, I wonder if it is possible to differentiate between ROLLBACK and COMMIT before displaying if rows were updated, so there will be less confusion."

Hmmm well the problem is I don't know if I have any control over what sqlalchemy echoes :/. Also there are already a lot of things to maintain and it's starting to get a bit complicated.

# Testing only one database

You can now run the tests on one or multiple databases, thanks for the suggestion!

# `future=True`

So I managed to prepare the library for Sqlalchemy v2. It should work when it gets out (unless there are some additional changes from sqlalchemy's side but this seems unlikely).

I am also working on an asynchronous version of `pangres.upsert` under the function [`pangres.aupsert`](https://github.com/ThibTrip/pangres/pull/42).

I am planning a major version release with sqlalchemy v2 compatibility and the new asynchronous function.
