### ISSUE TITLE
Feature Request: add a return value from `pangres.upsert` that shows how many rows were inserted, updated, etc.

### ISSUE THREAD

**Issue by DeflateAwning** [ThibTrip/pangres#69]
This is a common feature in other software like DBeaver, where the result of running a query shows how many rows were inserted, updated, deleted, etc. It would be valuable if such feedback could be added to this awesome library.

**Comment by ThibTrip** [comment]
Hello @DeflateAwning , sorry for the delay and thanks for the kind words 😄.

There is already such a feature. By default, `pangres.upsert` does not return anything, but if you set `yield_chunks=True`, you get an iterator back (more precisely, a generator, see example below). Note that you always get an iterator even with `chunksize=None` (the default).

This iterator allows you to iterate over the results (`sqlalchemy.engine.cursor.CursorResult` objects) of the upsert operations.

```python
import pandas as pd
from pangres import upsert
from sqlalchemy import create_engine


# create a SQLalchemy engine and some DataFrame for the example
engine = create_engine("sqlite://")
df = pd.DataFrame({'id': [1, 2], 'name': ['Test', 'Test2']}).set_index('id')

# prepare upsert (this does not execute any SQL queries yet because we get a generator ->
# if you don't know what that is, see https://wiki.python.org/moin/Generators)
generator = upsert(con=engine, df=df, table_name='example', if_row_exists='update', yield_chunks=True,
                   chunksize=None)  # chunksize=None is the default -> the upsert is done in a single chunk

# read from the generator -> executes SQL queries for the upsert and for each chunk of data upserted,
# you get a CursorResult object, allowing you to retrieve information such as the updated row count
for cursor_result in generator:
    print(cursor_result)
    # output: <sqlalchemy.engine.cursor.CursorResult object at 0x123456789>
    print(cursor_result.rowcount)
    # output: 2 (which means 2 rows where updated)
```

I hope this answers your question.

If you need more advanced inspection, you will need to build your own queries (e.g. if you want to return the upserted ids), because this falls out of scope for this library. For building your own queries, you can get some inspiration from the [upsert_query](https://github.com/ThibTrip/pangres/blob/master/pangres/upsert_query.py) module.
